//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moms_website.Resources._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rooms.
        /// </summary>
        public static string All_Rooms {
            get {
                return ResourceManager.GetString("All Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Room.
        /// </summary>
        public static string Double_Room {
            get {
                return ResourceManager.GetString("Double Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        public static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Room.
        /// </summary>
        public static string Family_Room {
            get {
                return ResourceManager.GetString("Family Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Møn.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Room.
        /// </summary>
        public static string Single_Room {
            get {
                return ResourceManager.GetString("Single Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rytterskolen Bed &amp; Breakfast.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Room.
        /// </summary>
        public static string Workshop_Room {
            get {
                return ResourceManager.GetString("Workshop Room", resourceCulture);
            }
        }
    }
}
